title: Curso-de-prueba
description: Esta es la descripcion del curso
template:
  repo: curso-de-prueba-template
  name: curso-de-prueba
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
